repoFolder: M:\Games\ModStaging\ZO_StarfieldMods_Repo\StarfieldMods ## This is the folder where you're storing your in-development mods'
useGit: true ## If you're using GitHub, set this to true'
gitHubRepo: https://github.com/ZeeOgre/StarfieldMods ## If you're using GitHub, this is the URL to your repository if useGit is true then this is required'
useModManager: true ## If you're using a mod manager, set this to true'
modStagingFolder: M:\Games\ModStaging\Starfield_Steam #if you're using a mod manager, this is the folder where your mod manager is looking for mods, if useModManager is true then this is required'
gameFolder: M:\SteamLibrary\steamapps\common\Starfield ## This is the folder where your game is installed if UseModManager is false, this is required. This functionality is not implemented yet.'
modManagerExecutable: S:\Games\Vortex\Vortex.exe ## If you're using a mod manager, this is the path to the executable for your mod manager, if useModManager is true then this is required'
modManagerParameters: --user-data S:\Games\VortexSteamData ## If you're using a mod manager, these are the launch parameters that may be required - for example if you want to use a custom profile in vortex'
ideExecutable: C:\Users\aggie\AppData\Local\Programs\Microsoft VS Code\Code.exe ## This is the path to your IDE, this is requred'
modStages: ## These are the stages that your mod will go through, you can add or remove stages as you see fit'
- "*DEV" ## This is the development stage, where you're actively working on the mod, the star indicates that it is the source folder, and there can only be one'
- TEST
- RELEASE
- "#NEXUS" ## these folders are archive folders, when a mod is packaged for deployment or deployed into the mod manager, these are primarily here for documentation, and should not be changed'
- "#DEPLOYED"
limitFiletypes: true ## You may want to include everything, or you may want to limit the filetypes moved and archived'
promoteIncludeFiletypes: ## These are the filetypes that will be included when promoting a mod from one stage to another'
- .esm
- .ba2
- .ini
- .txt
packageExcludeFiletypes: ## These are the filetypes that will be excluded when packaging a mod for deployment, we'll be creating folder backups, but will make sure to exclude these if present'
- .zip
- .7z
- .rar
archiveFormat: zip ##supported options are zip and 7z
timestampFormat: yyMMddHHmm ## format for timestamps in filenames - see https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes for options
myNameSpace: ZeeOgre ## This is your namespace, as a best practice any scripts you create should go into your own namespace, this will facilitate this tools ability to retreive "strays" which may be left by the mod manager'
myResourcePrefix: ZO_ ## When creating any other kinds of objects, use a consistent naming prefix so you can easily locate those resources, this will also help the tool retreive other "strays"'
showSaveMessage: false ## This will show a message box when a save is complete, this is useful if you're running the tool in the background and want to know when it's done'
showOverwriteMessage: false ## This will show a message box when a file is about to be overwritten, '
nexusAPIKey: E7SKr5C5BGJE/IfPvKhYLl+is6SI0hfBlxG12EiwSSwX--6zX4iFUvU5dSWaqz--YD7/HX4ZLnBB8qCr8Unj8w== ## This is your Nexus API key, at the moment, features using this are not implemented'
