repoFolder: D:\GitRepos\ZO.StarfieldMods
useGit: true
gitHubRepo: https://github.com/ZeeOgre/ZO.StarfieldMods
useModManager: true
modStagingFolder: D:\Games\Starfield\mods
gameFolder: D:\Games\Starfield\Content
modManagerExecutable: C:\Program Files\Black Tree Gaming Ltd\Vortex\Vortex.exe
modManagerParameters: ''
ideExecutable: '"C:\Program Files\Microsoft VS Code\Code.exe"'
modStages:
- '*DEV'
- TEST
- RELEASE
- '#NEXUS'
- '#DEPLOYED'
limitFiletypes: true
promoteIncludeFiletypes:
- .esm
- .ba2
- .ini
- .txt
packageExcludeFiletypes:
- .zip
- .7z
- .rar
timestampFormat: yyMMddHHmm
archiveFormat: zip
myNameSpace: ZeeOgre
myResourcePrefix: ZO_
showSaveMessage: false
showOverwriteMessage: false
nexusAPIKey: ''
autoCheckForUpdates: false
